global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'mortgage-orchestrator'
    static_configs:
      - targets: ['orchestrator:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'mortgage-pricing-service'
    static_configs:
      - targets: ['pricing-service:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'mortgage-prediction-service'
    static_configs:
      - targets: ['prediction-service:5002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']