# Secret for AWS credentials
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mortgage-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: # base64 encoded
  AWS_SECRET_ACCESS_KEY: # base64 encoded
